name: Simple job

on:
  push:
    branches:
    - master
    
jobs:
  simple-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Linter project
        uses: github/super-linter@v4.9.7

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simplejsproject .

      - name: Pushing to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simplejsproject
